# Visit https://github.com/lowlighter/metrics/blob/master/source/plugins/achievements/README.md for full reference
name: Achievements
on:
  schedule: [{ cron: "0 */12 * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics.plugin.achievements.svg

          # Options
          user: gthaka
          base: ""
          config_timezone: Africa/Nairobi
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X

          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
