# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Compact display (Achievements)
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 * * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master","main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Current configuration doesn't require a GitHub token
          filename: assets/metrics.plugin.achievements.compact.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          base: ""
          config_timezone: Africa/Nairobi
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
