# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Stared Topics
on:
  schedule: [{ cron: "0 */14 * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.stared-topics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 12
          # Options
          user: ${{ github.repository_owner }}
          config_timezone: Africa/Nairobi
