# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: WakaTime
on:
  schedule: [{ "cron": "*/30 * * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Current configuration doesn't require a GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          filename: assets/metrics.plugin.wakatime.svg

          # Options
          user: gthaka
          template: classic
          base: ""
          config_timezone: Africa/Nairobi
          plugin_wakatime: yes
          plugin_wakatime_days: 365
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, languages, languages-graphs, editors, editors-graphs, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: current
